package panyl

import (
	"context"
)

const DefaultScannerBufferSize = 1024 * 1024

// LineProvider provides lines to be parsed by Processor. It is usually a wrapper for bufio.Scanner, but may
// provide lines from any source
type LineProvider interface {
	// Err returns the first non-EOF error that was encountered by the LineProvider.
	Err() error
	// Line returns the most recent data generated by a call to Scan. This can be either a string, or a
	// *Process instance.
	// If returning *Process instances, usually only Process.Data should be filled.
	Line() any
	// Scan advances the Scanner to the next token, which will then be
	// available through the Line method. It returns false when the
	// scan stops, either by reaching the end of the input or an error.
	// After Scan returns false, the Err method will return any error that
	// occurred during scanning, except that if it was io.EOF, Err
	// will return nil.
	Scan(ctx context.Context) bool
}

