package panyl

import (
	"bufio"
	"fmt"
	"io"
)

const DefaultScannerBufferSize = 1024 * 1024

// LineProvider provides lines to be parsed by Processor. It is usually a wrapper for bufio.Scanner, but may
// provide lines from any source
type LineProvider interface {
	// Err returns the first non-EOF error that was encountered by the LineProvider.
	Err() error
	// Line returns the most recent data generated by a call to Scan. This can be either a string, or a
	// *Process instance.
	// If returning *Process instances, usually only Process.Data should be filled.
	Line() interface{}
	// Scan advances the Scanner to the next token, which will then be
	// available through the Line method. It returns false when the
	// scan stops, either by reaching the end of the input or an error.
	// After Scan returns false, the Err method will return any error that
	// occurred during scanning, except that if it was io.EOF, Err
	// will return nil.
	Scan() bool
}

// ReaderLineProvider is a LineProvider that reads from an io.Reader
type ReaderLineProvider struct {
	scanner *bufio.Scanner
}

func NewReaderLineProvider(r io.Reader, bufferSize int) LineProvider {
	scanner := bufio.NewScanner(r)
	if bufferSize > 0 {
		// adjust the scanner capacity
		buf := make([]byte, bufferSize)
		scanner.Buffer(buf, bufferSize)
	}
	return &ReaderLineProvider{scanner: scanner}
}

func (r *ReaderLineProvider) Err() error {
	return r.scanner.Err()
}

func (r *ReaderLineProvider) Line() interface{} {
	return r.scanner.Text()
}

func (r *ReaderLineProvider) Scan() bool {
	return r.scanner.Scan()
}

// StaticLineProvider is a LineProvider that reads from a memory array
type StaticLineProvider struct {
	currentLine int
	lines       []interface{}
	err         error
}

func NewStaticLineProvider(lines []interface{}) LineProvider {
	return &StaticLineProvider{currentLine: -1, lines: lines, err: nil}
}

func (r *StaticLineProvider) Err() error {
	return r.err
}

func (r *StaticLineProvider) Line() interface{} {
	if r.err != nil {
		return nil
	}

	if r.currentLine >= 0 && r.currentLine < len(r.lines) {
		return r.lines[r.currentLine]
	}
	r.err = fmt.Errorf("invalid index being read: %d", r.currentLine)
	return nil
}

func (r *StaticLineProvider) Scan() bool {
	if r.err != nil {
		return false
	}

	if r.currentLine >= len(r.lines)-1 {
		return false
	}
	r.currentLine++
	return true
}
